name: monitor

on:
  schedule:
    - cron: "*/5 * * * *"
  repository_dispatch:
    types: [run-monitor, pause, resume, set-interval]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
